language: d
sudo: false

matrix:
  include:
    - d: dmd-2.073.0
      env:
        - [FRONTEND=2.073]
        - [COVERAGE=true]
    - d: dmd-2.073.0
      env: [FRONTEND=2.073]
      os: osx
    - d: dmd-2.072.2
      env: [FRONTEND=2.072]
    - d: dmd-2.071.2
      env: [FRONTEND=2.071]
    - d: dmd-2.070.2
      env: [FRONTEND=2.070]
    - d: dmd-2.069.2
      env: [FRONTEND=2.069]
    - d: dmd-2.068.2
      env: [FRONTEND=2.068]
    - d: dmd-2.067.1
      env: [FRONTEND=2.067]
    - d: dmd-2.066.1
      env: [FRONTEND=2.066]
    - d: dmd-2.065.0
      env: [FRONTEND=2.065]
    - d: ldc-1.1.0-beta6
      env: [FRONTEND=2.071]
    - d: ldc-1.1.0-beta6
      env: [FRONTEND=2.071]
      os: osx
    - d: ldc-1.0.0
      env: [FRONTEND=2.070]
    - d: ldc-1.0.0
      env: [FRONTEND=2.070]
      os: osx
    - d: ldc-0.17.2
      env: [FRONTEND=2.068]
    - d: ldc-0.16.1
      env: [FRONTEND=2.067]
    - d: ldc-0.15.1
      env: [FRONTEND=2.066]
    - d: ldc-0.14.0
      env: [FRONTEND=2.065]
    - d: gdc-5.2.0
      env: [FRONTEND=2.066]
    - d: gdc-4.9.2
      env: [FRONTEND=2.066]
    - d: gdc-4.9.0
      env: [FRONTEND=2.065]
  allow_failures:
  - d: ldc-1.1.0-beta6

install:
 - if [ $TRAVIS_OS_NAME == osx ];
   then
     brew install jq;
   fi

script:
  - ./travis-ci.sh
